"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowUpDown, CheckCircle2, Clock3, Search } from "lucide-react"
import { useOutreachTasks } from "@/lib/hooks"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { formatPriority, formatShortDate, formatTaskType } from "@/components/outreach/outreach-utils"

export function OutreachTasksWorkspace() {
  const { tasks } = useOutreachTasks()
  const [searchValue, setSearchValue] = useState("")
  const [typeFilter, setTypeFilter] = useState("all")
  const [priorityFilter, setPriorityFilter] = useState("all")
  const referenceNow = new Date("2026-03-26T12:00:00Z").getTime()

  const filteredTasks = useMemo(
    () =>
      tasks.filter((task) => {
        const query = searchValue.trim().toLowerCase()
        const matchesQuery =
          query.length === 0 ||
          task.title.toLowerCase().includes(query) ||
          task.contactName.toLowerCase().includes(query) ||
          task.company.toLowerCase().includes(query)
        const matchesType = typeFilter === "all" || task.type === typeFilter
        const matchesPriority = priorityFilter === "all" || task.priority === priorityFilter

        return matchesQuery && matchesType && matchesPriority
      }),
    [priorityFilter, searchValue, tasks, typeFilter]
  )

  const overdueTasks = filteredTasks.filter((task) => new Date(task.dueAt).getTime() < referenceNow).length
  const callTasks = filteredTasks.filter((task) => task.type === "call").length
  const manualEmailTasks = filteredTasks.filter((task) => task.type === "manual_email").length

  return (
    <div className="grid gap-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm uppercase tracking-[0.18em] text-muted-foreground">All tasks</p>
            <p className="mt-3 text-3xl font-semibold">{filteredTasks.length}</p>
            <p className="mt-2 text-sm text-muted-foreground">Manual work created by seller replies, pauses and qualification steps.</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm uppercase tracking-[0.18em] text-muted-foreground">Call tasks</p>
            <p className="mt-3 text-3xl font-semibold">{callTasks}</p>
            <p className="mt-2 text-sm text-muted-foreground">Phone follow-up tasks generated by seller sequences.</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm uppercase tracking-[0.18em] text-muted-foreground">Manual email</p>
            <p className="mt-3 text-3xl font-semibold">{manualEmailTasks}</p>
            <p className="mt-2 text-sm text-muted-foreground">Human-crafted steps that should never run through bulk delivery infrastructure.</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm uppercase tracking-[0.18em] text-muted-foreground">Overdue</p>
            <p className="mt-3 text-3xl font-semibold">{overdueTasks}</p>
            <p className="mt-2 text-sm text-muted-foreground">Tasks needing immediate seller attention.</p>
          </CardContent>
        </Card>
      </div>

      <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex flex-1 flex-col gap-3 lg:flex-row lg:items-center">
          <div className="relative flex-1">
            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={searchValue}
              onChange={(event) => setSearchValue(event.target.value)}
              placeholder="Search tasks"
              className="pl-9"
            />
          </div>
          <Select value={typeFilter} onValueChange={setTypeFilter}>
            <SelectTrigger className="w-full lg:w-[220px]">
              <SelectValue placeholder="All task types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All task types</SelectItem>
              <SelectItem value="call">Call</SelectItem>
              <SelectItem value="manual_email">Manual email</SelectItem>
              <SelectItem value="linkedin">LinkedIn</SelectItem>
              <SelectItem value="action_item">Action item</SelectItem>
            </SelectContent>
          </Select>
          <Select value={priorityFilter} onValueChange={setPriorityFilter}>
            <SelectTrigger className="w-full lg:w-[220px]">
              <SelectValue placeholder="All priorities" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All priorities</SelectItem>
              <SelectItem value="high">High</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="low">Low</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" asChild>
            <Link href="/outreach/sequences">Open sequences</Link>
          </Button>
          <Button>Create task</Button>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock3 className="size-5 text-muted-foreground" />
              Seller task queue
            </CardTitle>
            <CardDescription>
              Daily work list for calls, manual emails, LinkedIn touches and cleanup items.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {filteredTasks.map((task) => (
              <div key={task.id} className="rounded-2xl border border-border p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="font-medium text-foreground">{task.title}</p>
                    <p className="mt-1 text-sm text-muted-foreground">{task.contactName} · {task.company}</p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge variant="outline">{formatTaskType(task.type)}</Badge>
                    <Badge variant="outline">{formatPriority(task.priority)}</Badge>
                  </div>
                </div>
                <div className="mt-3 grid gap-3 text-sm text-muted-foreground md:grid-cols-3">
                  <p>Owner: <span className="text-foreground">{task.ownerName}</span></p>
                  <p>Due: <span className="text-foreground">{formatShortDate(task.dueAt)}</span></p>
                  <p>Sequence: <span className="text-foreground">{task.sequenceName ?? "Direct 1:1"}</span></p>
                </div>
                {task.note ? <p className="mt-3 text-sm text-muted-foreground">{task.note}</p> : null}
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CheckCircle2 className="size-5 text-muted-foreground" />
                Task model
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Automatic email steps do not create a task because they send on schedule.</p>
              <p>Manual email, call and action steps surface here for the seller to complete.</p>
              <p>Sequence stops on reply or interested status should immediately reduce future pending work.</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ArrowUpDown className="size-5 text-muted-foreground" />
                Suggested views
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>All tasks</p>
              <p>Call tasks</p>
              <p>Email tasks</p>
              <p>LinkedIn tasks</p>
              <p>Overdue tasks</p>
              <p>My tasks</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Relationship CRM boundary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>These tasks are seller work generated from inbox threads and seller sequences.</p>
              <p>They should never be mixed with campaign production or broadcast execution queues.</p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
